language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:  
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
script: 
  - flake8 readit setup.py
  - python setup.py install
  - readit --version
