#!/bin/bash

if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
    if [ $OS == "Fedora" ]; then
            echo "=========================================="
            echo "============Welcome User ================="
            echo "=========================================="
             VER=$VERSION_ID
             if [ $VER == 26 ]; then
                     echo "$OS $VER"
		     dnf install https://download.postgresql.org/pub/repos/yum/10/fedora/fedora-26-x86_64/pgdg-fedora10-10-3.noarch.rpm -y
		     dnf install postgresql10 postgresql10-server -y
		     dnf install pgadmin3 phppgadmin -y
		     /usr/pgsql-10/bin/postgresql-10-setup initdb
                     
		     # Modification /var/lib/pgsql/10/data/pg_hba.conf Note: User will do manually 
                      echo "==================================================="
                      echo "==================================================="
                      echo " Note: Modify /var/lib/pgsql/10/data/pg_hba.conf"
                      echo "For that please Read instruction from README.md"
                      echo "==================================================="
                      echo "==================================================="
		     
		     systemctl start postgresql-10.service
		     systemctl enable postgresql-10.service

		     #Creating Test Database and Create New User
                     useradd postgres
                     mkdir /usr/pgsql-10/data
                     chown postgres:postgres /usr/pgsql-10/data
                     su - postgres -c "/usr/pgsql-10/bin/initdb /usr/pgsql-10/data/; sleep 2s; /usr/pgsql-10/bin/pg_ctl -D /usr/pgsql-10/data/ -l logfile start"
                     firewall-cmd --permanent --zone=public --add-service=postgresql
                     firewall-cmd --permanent --zone=public --add-port=5432/tcp
                     systemctl restart firewalld.service
                     systemctl enable firewalld.service

	     elif [ $VER == 27 ]; then
                     echo "$OS $VER"
		     dnf install https://download.postgresql.org/pub/repos/yum/10/fedora/fedora-27-x86_64/pgdg-fedora10-10-3.noarch.rpm  -y
		     dnf install postgresql10 postgresql10-server -y
		     dnf install pgadmin3 phpPgAdmin -y
		     /usr/pgsql-10/bin/postgresql-10-setup initdb

		     # Modification /var/lib/pgsql/10/data/pg_hba.conf
		      echo "==================================================="
		      echo "==================================================="
                      echo " Note: Modify /var/lib/pgsql/10/data/pg_hba.conf"
		      echo "For that please Read instruction from README.md"
                      echo "==================================================="
                      echo "==================================================="

		     systemctl start postgresql-10.service
                     systemctl enable postgresql-10.service

		     #Creating Test Database and Create New User

                     useradd postgres
		     mkdir /usr/pgsql-10/data
		     chown postgres:postgres /usr/pgsql-10/data
		     su - postgres -c "/usr/pgsql-10/bin/initdb /usr/pgsql-10/data/; sleep 2s; /usr/pgsql-10/bin/pg_ctl -D /usr/pgsql-10/data/ -l logfile start"
		     firewall-cmd --permanent --zone=public --add-service=postgresql
                     firewall-cmd --permanent --zone=public --add-port=5432/tcp
		     systemctl restart firewalld.service
                     systemctl enable firewalld.service
	     fi
    fi
fi 
