name: Publish readit to PyPI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and publish readit distributions to PyPI
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout to master
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Build Package
        run: |
          python -m pip install --upgrade setuptools wheel twine
          python setup.py sdist bdist_wheel

      - name: Package check
        run: twine check dist/*

      - name: Deploy to PyPi readit
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_readit }}
